### ISSUE TITLE
Implementation of extra functionality from lodash

### ISSUE THREAD

**Issue by thijsmie** [twisterghost/gdash#9]
The following functions are in lodash that seem useful in GM context:

_chunk
_difference
_drop
_fill
_intersection
_pull
_reverse
_slice
_union
_without
_zip

**Comment by trouvant** [comment]
I've cloned the repository and am writing implementations and documentation for each of these functions, as well as any logical counterparts to them (such as _unzip for _zip). So far, I've written _union, _intersection, _fill, _chunk, _zip, and _unzip. I'll make a pull request for these in a few days, once I've finished and optimized them all.

**Comment by twisterghost** [comment]
Awesome. Be aware of #12 while doing so. I'm currently working on version 4.0 which will have a few fundamental changes, such as dropping GM:S1.4 support and standardizing naming schemes on using underscore case rather than camelcase (`_hello_world` instead of `_helloWorld`).

I'm happy to accept a PR to the v4 branch if you'd like to get ahead of the game there. Functionally, its nearly ready, just making some more convenience things for deployment and documentation generation.

**Comment by trouvant** [comment]
Absolutely. I was excited to see some new activity on the repository, and I'll be happy to ensure my contribution is consistent with the new standards and with the new GMS2 engine. For the sake of efficiency, all the scripts I'm adding are independent of any of the other scripts in the library, so changes to any existing functionality of GDash won't be a problem.
